# Input/output configuration
input_dir: /global/cscratch1/sd/danieltm/ExaTrkX/trackml/feature_store_endcaps
output_dir: global/cscratch1/sd/danieltm/ExaTrkX/trackml_processed/embedding_processed/0_pt_cut_endcaps
project: EmbeddingStudy
overwrite: True
n_workers: 1

# Dataset parameters
pt_min: 0
train_split: [6, 2, 2] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 12
emb_hidden: 512
nb_layer: 6
emb_dim: 8
weight: 4
randomisation: 2
clustering: build_edges  # or radius_graph
r_train: 1
r_val: 1.5
knn_train: 20
knn_val: 100
warmup: 500
margin: 1
lr: 0.002
factor: 0.3
patience: 5
regime:
    - rp # Random pairs: Trains with pairs in hinge loss selected randomly
    - hnm # Hard negative mining: Trains with
    - ci
max_epochs: 2
wandb_save_dir: /mnt/d/Documents/MachineLearning/ExaTrkx/IML2020/trained_results